package com.hashmi.familylink.data

import kotlinx.serialization.Serializable

/**
 * Content encoded into Family Link QR codes.
 *
 * - [KIND_CLIENT]: generated by the Client so the Server can authorize it.
 * - [KIND_SERVER]: generated by the Server so the Client can connect directly
 *   when UDP discovery is blocked. It also carries the hub's [deviceId] and
 *   [pairingKey], and — when a relay is configured — its [relayUrl], so the
 *   very first pairing can happen over the internet without a shared Wi‑Fi.
 */
@Serializable
data class QrPayload(
    val kind: String,
    val deviceId: String = "",
    val pairingKey: String = "",
    val deviceName: String = "",
    val host: String = "",
    val port: Int = DEFAULT_PORT,
    /** Relay server address the client should dial (blank for LAN-only hubs). */
    val relayUrl: String = ""
) {
    fun isClientPairing(): Boolean =
        kind == KIND_CLIENT && pairingKey.isNotBlank() && deviceId.isNotBlank()

    fun isServerInvite(): Boolean =
        kind == KIND_SERVER && host.isNotBlank() && port > 0

    companion object {
        const val KIND_CLIENT = "client"
        const val KIND_SERVER = "server"
        const val DEFAULT_PORT = 8080

        fun client(deviceId: String, pairingKey: String, deviceName: String): QrPayload =
            QrPayload(
                kind = KIND_CLIENT,
                deviceId = deviceId,
                pairingKey = pairingKey,
                deviceName = deviceName
            )

        /**
         * @param deviceId the hub's stable device id
         * @param pairingKey the hub's own pairing key
         * @param relayUrl the hub's relay server, when one is configured
         */
        fun server(
            host: String,
            port: Int,
            serverName: String,
            deviceId: String = "",
            pairingKey: String = "",
            relayUrl: String = ""
        ): QrPayload = QrPayload(
            kind = KIND_SERVER,
            host = host,
            port = port,
            deviceName = serverName,
            deviceId = deviceId,
            pairingKey = pairingKey,
            relayUrl = relayUrl
        )
    }
}

fun encodeQrPayload(payload: QrPayload): String =
    JsonConfig.json.encodeToString(QrPayload.serializer(), payload)

fun decodeQrPayload(raw: String): QrPayload? {
    val trimmed = raw.trim()
    if (trimmed.isEmpty()) return null
    return try {
        JsonConfig.json.decodeFromString(QrPayload.serializer(), trimmed)
    } catch (_: Exception) {
        // Allow pasting just a pairing key (XXXX-XXXX) as a fallback.
        val key = trimmed.uppercase()
        if (PAIRING_KEY_REGEX.matches(key)) {
            QrPayload(kind = QrPayload.KIND_CLIENT, pairingKey = key, deviceId = key)
        } else {
            null
        }
    }
}

val PAIRING_KEY_REGEX = Regex("^[A-Z2-9]{4}-[A-Z2-9]{4}$")
