package com.hashmi.familylink.data

import kotlinx.serialization.Serializable

/**
 * Content encoded into Family Link QR codes.
 *
 * - [KIND_CLIENT]: generated by the Client so the Server can authorize it.
 * - [KIND_SERVER]: generated by the Server so the Client can connect directly
 *   when UDP discovery is blocked.
 */
@Serializable
data class QrPayload(
    val kind: String,
    val deviceId: String = "",
    val pairingKey: String = "",
    val deviceName: String = "",
    val host: String = "",
    val port: Int = DEFAULT_PORT
) {
    fun isClientPairing(): Boolean =
        kind == KIND_CLIENT && pairingKey.isNotBlank() && deviceId.isNotBlank()

    fun isServerInvite(): Boolean =
        kind == KIND_SERVER && host.isNotBlank() && port > 0

    companion object {
        const val KIND_CLIENT = "client"
        const val KIND_SERVER = "server"
        const val DEFAULT_PORT = 8080

        fun client(deviceId: String, pairingKey: String, deviceName: String): QrPayload =
            QrPayload(
                kind = KIND_CLIENT,
                deviceId = deviceId,
                pairingKey = pairingKey,
                deviceName = deviceName
            )

        fun server(host: String, port: Int, serverName: String): QrPayload =
            QrPayload(
                kind = KIND_SERVER,
                host = host,
                port = port,
                deviceName = serverName
            )
    }
}

fun encodeQrPayload(payload: QrPayload): String =
    JsonConfig.json.encodeToString(QrPayload.serializer(), payload)

fun decodeQrPayload(raw: String): QrPayload? {
    val trimmed = raw.trim()
    if (trimmed.isEmpty()) return null
    return try {
        JsonConfig.json.decodeFromString(QrPayload.serializer(), trimmed)
    } catch (_: Exception) {
        // Allow pasting just a pairing key (XXXX-XXXX) as a fallback.
        val key = trimmed.uppercase()
        if (PAIRING_KEY_REGEX.matches(key)) {
            QrPayload(kind = QrPayload.KIND_CLIENT, pairingKey = key, deviceId = key)
        } else {
            null
        }
    }
}

val PAIRING_KEY_REGEX = Regex("^[A-Z2-9]{4}-[A-Z2-9]{4}$")
